server:
  port: 8081
spring:
  application:
    name: book-service
  #配置数据库相关
  datasource:
    url: jdbc:mysql://localhost:3306/reading?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sql123456

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 整挺好接口文档
    description: "Reading接口文档"
    email: 123456@gmail.com
    concat: XX
    url: https://www.baidu.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.fylan.book_service.controller